Дисциплина «Искусственный интеллект» Рабочая тетрадь № 2

Цель машинного обучения – анализ данных.
Данные – зарегистрированная информация; представление фактов, понятий или инструкций в форме, приемлемой для общения, интерпретации, или обработки человеком или с помощью автоматических средств (ISO/IEC/IEEE 24765-2010).
Данные в машинном обучении – это представление информации об исследуемой задаче в виде множеств исследуемых объектов и множеств их характеристик, на основе которых строятся модели, разрабатываются подходы, методы и алгоритмы анализа для принятия решений.
Качество данных – важный аспект машинного обучения.
Для Аналитика (Data Scientist, Data Analyst, Data Mining Engineer) очень важно обладать правильными данными, что гарантирует эффективность обработки и построении прогнозов. На рисунке 1 представлены основные требования к данным.



Остановимся	на	основных	этапах	решения	задач	машинного обучения.
Этапы решения задач машинного обучения:
1.Постановка задачи.
2.Сбор и подготовка данных.
3.Предобработка данных и выделение ключевых признаков.
4.Выбор алгоритмов машинного обучения.
5.Обучение модели (моделей).
6.Оценка качества.
7.Эксплуатация модели.
При подготовке данных можно применять следующие операции:
-структурирование – приведение данных к табличному (матричному)
виду;
-заполнение пропусков;

-отбор – исключение записей с отсутствующими или некорректными значениями, если нет возможности заполнения и устранения противоречивости;
-нормализация – приведение числовых значений к определенному диапазону, например к диапазону 0...1;
-кодирование – это представление категориальных данных в числовой форме.



1.1. Теоретический материал – Библиотека NumPy
NumPy (NumericalPython) - это библиотека Python с открытым исходным кодом, которая используется практически во всех областях науки и техники. Это универсальный стандарт для работы с числовыми данными в Python.
Если у вас уже есть Python, вы можете установить NumPy с помощью командной строки:
pip install numpy
Чтобы начать использовать NumPy необходимо импортировать соответствующую библиотеку:
import numpy as np
Основным объектом NumPy является однородный многомерный массив (в numpy называется numpy.ndarray). Это многомерный массив элементов (обычно чисел), одного типа.
Наиболее важные атрибуты объектов ndarray:
ndarray.ndim - число измерений (чаще их называют "оси") массива.
ndarray.shape - размеры массива, его форма. Это кортеж натуральных чисел, показывающий длину массива по каждой оси. Для матрицы из n строк и m столбов, shape будет (n,m). Число элементов кортежа shape равно ndim. ndarray.size -	количество	элементов	массива.	Очевидно,	равно
произведению всех элементов атрибута shape.
ndarray.dtype - объект, описывающий тип элементов массива. Можно определить dtype, используя стандартные типы данных Python. NumPy здесь предоставляет целый букет возможностей, как встроенных, например: bool_, character, int8, int16, int32, int64, float8, float16, float32, float64, complex64, object_, так и возможность определить собственные типы данных, в том числе и составные.
ndarray.itemsize - размер каждого элемента массива в байтах.
ndarray.data - буфер, содержащий фактические элементы массива. Обычно не нужно использовать этот атрибут, так как обращаться к элементам массива проще всего с помощью индексов.
Подробнее о массивах в NumPy можно найти в официальной документации https://numpy.org/doc/stable/user/absolute_beginners.html

1.2.1 Пример

Задача:
	Создать массив 5x2. Создать массив 5x2. Вывести все значения массива, значение элемента с индексом (3,1) и второй столбец. Индексация
начинается с нуля.

In [16]:
import numpy as np
x = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10]])
print(x)
print(x[3][1])
print(x[1])

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
8
[3 4]


1.2.2 Пример
Задача:
	Пример. Выполнить следующее:
1.Создать вектор (одномерный массив) размера 10, заполненный нулями.
2.Создать вектор размера 10, заполненный единицами.
3.Создать вектор размера 10, заполненный заданным числом.
4.Создать вектор со значениями от 10 до 19.

In [17]:
a = np. zeros(10)
b = np. ones(10)
c= np.full(10, 5)
d = np.arange(10, 20)
print(a, "\n", b, "\n", c, "\n", d)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] 
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.] 
 [5 5 5 5 5 5 5 5 5 5] 
 [10 11 12 13 14 15 16 17 18 19]


1.2.3 Пример

Задача:
	Создать массив 10x10 со случайными значениями, найти минимум,
максимум и среднее значение.

In [18]:
Z = np.random.random((10,10))
Zmin, Zmax, Zmean = Z.min(), Z.max(), Z.mean()
print(Zmin, Zmax, Zmean)

0.004773069866534918 0.99221030747097 0.4914525558316473


1.2.4 Пример
Задача:
	Задать матрицу размерности 5 на 5 и поменять 2 строки в матрице
местами.

In [19]:
A = np.arange(25).reshape(5,5)
A[[0,1]] = A[[1,0]]
print(A)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


1.2.5 Пример
Задача:
	Выяснить результат следующих выражений: 0 * np.nan
np.nan == np.nan np.inf > np.nan np.nan - np.nan 0.3 == 3 * 0.1

In [20]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(0.3 == 3 * 0.1)

nan
False
False
nan
False


1.2.6 Пример
Задача:
	Отсортировать массив.

In [21]:
arr = np. array([2, 1, 5, 3, 7, 4, 6, 8])
print(np.sort(arr))

[1 2 3 4 5 6 7 8]


1.3.1 Задание
Задача:
	Создать 8x8 матрицу и заполнить её в шахматном порядке нулями и
единицами.

In [22]:
import numpy as np

a = np.arange(64).reshape(8, 8)
for x in range(8):
    for y in range(8):
        if (x + 1 + y + 1)%2 == 0:
            a[x][y] = 1
        else:
            a[x][y]=0
print(a)

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


1.3.2 Задание
Задача:
	Создать 5x5 матрицу со значениями в строках от 0 до 4. Для создания
необходимо использовать функцию arange.

In [23]:
import numpy as np

a = np.arange(25).reshape(5,5)

for x in range(5):
    for y in range(5):
        a[x][y]=y


print(a)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


1.3.3 Задание
Задача:
	Создать массив 3x3x3 со случайными значениями.

In [24]:
import numpy as np
import random as r

a = np.arange(27).reshape(3,3,3)

for x in range(3):
    for y in range(3):
        for z in range(3):
            a[x][y][z] = r.randint(1,1000)

print(a)

[[[962 505 281]
  [178 767 312]
  [723  90 885]]

 [[269 126 959]
  [577 430  17]
  [287 883 564]]

 [[599 144 606]
  [624 397 335]
  [660 102  60]]]


1.3.4 Задание
Задача:

	Создать матрицу с 0 внутри, и 1 на границах.

In [25]:
import numpy as np

Z = np.ones((10,10))

Z[1:-1,1:-1] = 0

print(Z)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


1.3.5 Задание
Задача:
	Создайте массив и отсортируйте его по убыванию.

In [26]:
import numpy as np
import random as r

n= int(input())

a = np.arange(n)
r.shuffle(a)
a = list(a)

a.sort()
a.reverse()

print(a)

[4, 3, 2, 1, 0]


1.3.6 Задание
Задача:
	Создайте матрицу, выведите ее форму, размер и размерность.

In [27]:
import numpy as np

n = int(input())
m = int(input())

a = np.arange(n*m).reshape(n,m)

n = a.shape[0]
m = a.shape[1]

if n>m or n<m:
    print(f'прямоугольная {n} строк и {m} столбцов, A{n}x{m}')
if n==m:
    print(f'квадратная {n} строк и {m} столбцов, A{n}x{m}')

квадратная 5 строк и 5 столбцов, A5x5


2.1. Теоретический материал – Библиотека Pandas
Первым шагом в любом начинании в области машинного обучения является введение исходных данных в систему. Исходные данные могут вводиться вручную, содержаться в файле или храниться в интернете в каком- либо формате. Кроме того, часто требуется получить данные из нескольких источников.
Библиотека pandas – это удобный и быстрый инструмент для работы с данными, обладающий большим функционалом. Если очень кратко, то pandas – это библиотека, которая предоставляет очень удобные с точки зрения использования инструменты для хранения данных и работе с ними.
Библиотека pandas присутствует в стандартной поставке Anaconda. Если же ее там нет, то его можно установить отдельно. Для этого введите командной строке:
pip install pandas
Для импорта библиотеки используйте команду:
import pandas as pd
Библиотека pandas предоставляет две ключевые структуры данных: Series и DataFrame.
Series – это одномерная структура данных, ее можно представить, как таблицу с одной строкой. С Series можно работать как с обычным массивом (обращаться по номеру индекса), и как с ассоциированным массивом, когда можно использовать ключ для доступа к элементам данных.
DataFrame – это двумерная структура. Идейно она очень похожа на обычную таблицу, что выражается в способе ее создания и работе с ее элементами.

2.2.1 Пример
	Задача:
		Создать Series из списка Python, словаря Python, и массива Numpy
(установить буквенные метки для последнего).

In [28]:
import pandas as pd
lst = [1, 2, 3, 4, 5]
d = {'a':1, 'b':2, 'c':3}
ndarr = np.array([1, 2, 3, 4, 5])
s1 = pd.Series(lst)
s2 = pd.Series(d)
s3 = pd.Series(ndarr, ['a', 'b', 'c', 'd', 'e'])
print(s1)
print(s2)
print(s3)

0    1
1    2
2    3
3    4
4    5
dtype: int64
a    1
b    2
c    3
dtype: int64
a    1
b    2
c    3
d    4
e    5
dtype: int32


2.2.2 Пример
	Задача:
		Дано два Series. Напечатать их первые элементы и все элементы после
третьего (во втором фрейме).

In [29]:
import pandas as pd
s1 = pd.Series([1, 2, 3, 4, 5], ['a', 'b', 'c', 'd', 'e'])
s2 = pd. Series([5, 4, 3, 2, 1])
print(s1['a'])
print(s2[0])
print(s2[3:])

1
5
3    2
4    1
dtype: int64


2.2.3 Пример
	Задача:
		Создайте новый фрейм данных.

In [30]:
dataframe = pd. DataFrame()
dataframe['Имя'] = ["Джеки Джексон', 'Стивен Стивенсон'] dataframe['Возраст'] = [38, 25] dataframe['Водитель"]
#dataframe['Водитель'] = [True, False]

2.2.4 Пример
	Задача:
		Загрузите фрейм данных по ссылке: https://raw.githubusercontent.com/chrisalbon/simulated_datasets/master/titan
ic.csv

In [31]:
# Создать URL-адрес
url = ' https://raw.githubusercontent.com/chrisalbon/simulated_datasets/master/titanic.csv '
# Загрузить данные
dataframe = pd.read_csv(url)
# Показать пять строк
dataframe. head(5)

OSError: [Errno 22] Invalid argument: ' https://raw.githubusercontent.com/chrisalbon/simulated_datasets/master/titanic.csv '

2.2.5 Пример
	Задача:
		Пронализировать характеристики фрейма данных.

In [33]:
dataframe.head(2)
dataframe. tail(3)
dataframe.shape
dataframe.describe()

Имя
count                                                   1
unique                                                  1
top     Джеки Джексон', 'Стивен Стивенсон'] dataframe[...
freq                                                    1

2.2.6 Пример
	Задача:
		Выберите индивидуальные данные или срезы фрейма данных.

In [34]:
dataframe.iloc[1:4]

Empty DataFrame
Columns: [Имя]
Index: []

2.2.7 Пример
	Задача:
		Требуется отобрать строки фрейма данных на основе	некоторого
условия. Необходимо сформировать новый фрейм данных из пассажиров первого класса.

In [35]:
dataframe[dataframe['PClass']=='1st'].head(2)

KeyError: 'PClass'

2.3.1 Задание
	Задача:
		Найдитн евклидово расстояние между двумя Series (точками) a и b, не
используя встроенную формулу.

In [38]:
import pandas as pd
import math as m

a = [int(input()),int(input())]
b = [int(input()),int(input())]

a = pd.Series(a)
b = pd.Series(b)

distance = m.sqrt(pow(a[0]-b[0],2)+pow(b[0]-a[0],2))

print(distance)

0.0


2.3.2 Задание
	Задача:
		Найдите в Интернете ссылку на любой csv файл и сформируйте из него фрейм данных (например, коллекцию фреймов данных можно найти
здесь: https://github.com/akmand/datasets).

In [39]:
import pandas as pd

df = pd.read_csv('ex.csv')
df.head()

Дата   Price   Откр.   Макс.    Мин.   Объём     Per
0  31 дек. 2021 г.  177,57  178,09  179,23  177,26  64,06M  -0,35%
1  30 дек. 2021 г.  178,20  179,47  180,57  178,09  59,77M  -0,35%
2  29 дек. 2021 г.  179,38  179,33  180,63  178,14  62,35M  -0,35%
3  28 дек. 2021 г.  179,29  180,16  181,33  178,53  79,14M  -0,35%
4  27 дек. 2021 г.  180,33  177,09  180,42  177,07  74,92M   2,30%

2.3.3 Задание
	Задача:
		Проделайте с получившемся из предыдущего задания фреймом данных
те же действия, что и в примерах 2.2.5-2.2.7.

In [40]:
import pandas as pd
import csv

#2.2.5-2.2.7

df = pd.read_csv('ex.csv')

print(df.head(2))
print(df.tail(3))
print(df.shape)
df.describe()

print(df.iloc[1:4])

print(df[df['Per']=="-0,35"].head(5))

              Дата   Price   Откр.   Макс.    Мин.   Объём     Per
0  31 дек. 2021 г.  177,57  178,09  179,23  177,26  64,06M  -0,35%
1  30 дек. 2021 г.  178,20  179,47  180,57  178,09  59,77M  -0,35%
                Дата   Price   Откр.   Макс.    Мин.    Объём     Per
249  06 янв. 2021 г.  126,60  127,72  131,05  126,38  155,09M  -3,37%
250  05 янв. 2021 г.  131,01  128,89  131,74  128,43   97,66M   1,24%
251  04 янв. 2021 г.  129,41  133,52  133,61  126,76  143,30M  -2,47%
(252, 7)
              Дата   Price   Откр.   Макс.    Мин.   Объём     Per
1  30 дек. 2021 г.  178,20  179,47  180,57  178,09  59,77M  -0,35%
2  29 дек. 2021 г.  179,38  179,33  180,63  178,14  62,35M  -0,35%
3  28 дек. 2021 г.  179,29  180,16  181,33  178,53  79,14M  -0,35%
Empty DataFrame
Columns: [Дата, Price, Откр., Макс., Мин., Объём, Per]
Index: []


3.1. Теоретический материал – Работа с числовыми данными
Количественные данные что-то измеряют – будь то размер класса, ежемесячные продажи или оценки учащихся. Естественным способом представления этих величин является численным (например, 150 студентов,
$529 392 продаж).
Нормализация данных — это общепринятая задача предобработки в машинном обучении. Многие алгоритмы предполагают, что все признаки находятся в единой шкале, как правило, от 0 до 1 или от -1 до 1.
Существует множество способов нормализации значений признаков, чтобы масштабировать их к единому диапазону и использовать в различных моделях машинного обучения. В зависимости от используемой функции, их можно разделить на 2 большие группы: линейные и нелинейные. При нелинейной нормализации в расчетных соотношениях используются функции логистической сигмоиды или гиперболического тангенса. В линейной нормализации изменение переменных осуществляется пропорционально, по линейному закону.
На практике наиболее распространены следующие методы нормализации признаков:
Минимакс – линейное преобразование данных в диапазоне [0..1], где минимальное и максимальное масштабируемые значения соответствуют 0 и 1 соответственно;
Z-масштабирование данных на основе среднего значения и стандартного отклонения: производят деление разницы между переменной и средним значением на стандартное отклонение.
При масштабировании данных мы будем использовать одну из популярных библиотек машинного обучения Scikit-learn. Библиотека содержит пакет sklearn.preprocessing, который предоставляет широкие возможности для нормализации данных. Следует отметить, что в целом алгоритмы обучения выигрывают от стандартизации набора данных.

3.2.1. Пример
Задача:
	Прошкалируйте числовой признак в диапазон между двумя значениями.

In [41]:
# Загрузить библиотеки
import numpy as np
from sklearn import preprocessing
# Создать признак
feature = np.array([[-500.5], [-100.1], [0], [100.1], [900.9]]) # Создать шкалировщик
minmax_scale = preprocessing.MinMaxScal(feature_range= (0, 1))
# Прошкалировать признак
scaled_feature = minmax_scale.fit_transform(feature)
#Показать прошкалированный признак
scaled_feature

AttributeError: module 'sklearn.preprocessing' has no attribute 'MinMaxScal'

3.2.2. Пример
Задача:
	Преобразуйте признак, чтобы он имел среднее значение 0 и стандартное
отклонение 1.

In [42]:
x = np.array([[-1000.1], [-200.2], [500.5], [600.6], [9000.9]]) # Создать шкалировщик
scaler = preprocessing.StandardScaler()
# Преобразовать признак
standardized = scaler.fit_transform(x)
# Показать признак
standardized

array([[-0.76058269],
       [-0.54177196],
       [-0.35009716],
       [-0.32271504],
       [ 1.97516685]])

3.2.3. Пример
Задача:
	Дан фрейм данных
dfTest = pd.DataFrame({'A':[14.00,90.20,90.95,96.27,91.21],
'B':[103.02,107.26,110.35,114.23,114.68],
'C':['big','small','big','small','small']}) Необходимо масштабировать его числовые столбцы.

In [43]:
import pandas as pd
from sklearn. preprocessing import MinMaxScaler
scaler = MinMaxScaler()
dfTest = pd.DataFrame({'A':[14.00,90.20,90.95,96.27,91.21],'B':[103.02,107.26,110.35,114.23,114.68],
'C':['big','small','big','small','small']})
dfTest[['A', 'B']] = scaler.fit_transform(dfTest[['A', 'B']])
dfTest

A         B      C
0  0.000000  0.000000    big
1  0.926219  0.363636  small
2  0.935335  0.628645    big
3  1.000000  0.961407  small
4  0.938495  1.000000  small

3.3.2 Задание
	Задача:
		Загрузить фрейм данных по ссылке: https://raw.githubusercontent.com/akmand/datasets/master/iris.csv. Необходимо выполнить нормализацию первого числового признака (sepal_length_cm) с использованием минимаксного преобразования, а
второго (sepal_width_cm) с задействованием z-масштабирования.

In [44]:
from sklearn.preprocessing import MinMaxScaler
from sklearn import preprocessing
import pandas as pd
import numpy as np
import csv

df = pd.read_csv("iris.csv")

keep_f1 = ['sepal.length']
keep_f2 = ['sepal.width']

min_max = df[keep_f1]
z_mash = df[keep_f2]

scaler = preprocessing.StandardScaler()
scaler.fit(z_mash)

min_max = preprocessing.normalize(min_max,norm='max',axis=0)
print(f"min max {min_max},z mash {scaler.transform(z_mash)}")

min max [[0.64556962]
 [0.62025316]
 [0.59493671]
 [0.58227848]
 [0.63291139]
 [0.6835443 ]
 [0.58227848]
 [0.63291139]
 [0.55696203]
 [0.62025316]
 [0.6835443 ]
 [0.60759494]
 [0.60759494]
 [0.5443038 ]
 [0.73417722]
 [0.72151899]
 [0.6835443 ]
 [0.64556962]
 [0.72151899]
 [0.64556962]
 [0.6835443 ]
 [0.64556962]
 [0.58227848]
 [0.64556962]
 [0.60759494]
 [0.63291139]
 [0.63291139]
 [0.65822785]
 [0.65822785]
 [0.59493671]
 [0.60759494]
 [0.6835443 ]
 [0.65822785]
 [0.69620253]
 [0.62025316]
 [0.63291139]
 [0.69620253]
 [0.62025316]
 [0.55696203]
 [0.64556962]
 [0.63291139]
 [0.56962025]
 [0.55696203]
 [0.63291139]
 [0.64556962]
 [0.60759494]
 [0.64556962]
 [0.58227848]
 [0.67088608]
 [0.63291139]
 [0.88607595]
 [0.81012658]
 [0.87341772]
 [0.69620253]
 [0.82278481]
 [0.72151899]
 [0.79746835]
 [0.62025316]
 [0.83544304]
 [0.65822785]
 [0.63291139]
 [0.74683544]
 [0.75949367]
 [0.7721519 ]
 [0.70886076]
 [0.84810127]
 [0.70886076]
 [0.73417722]
 [0.78481013]
 [0.70886076]
 [0.74683544